### ISSUE TITLE
page 404 

### ISSUE THREAD

**Issue by Aissaoui-Ahmed** [linuxscout/fareh#1]
Hi @linuxscout !
Page of Wikipedia deleted by [صالح](https://ar.wikipedia.org/wiki/%D9%85%D8%B3%D8%AA%D8%AE%D8%AF%D9%85:%D8%B5%D8%A7%D9%84%D8%AD) and page [AUTHORS](https://github.com/linuxscout/fareh/master/AUTHORS.md) Not Found

![mohamed-ferah](https://user-images.githubusercontent.com/20658625/70807718-5da04e00-1dbe-11ea-91c8-0e69e0235868.png)

**Comment by linuxscout** [comment]
لقد كتبتها وحذفوها، لذا وضعتها في الموقع
