### ISSUE TITLE
قائمة أخطاء لغوية

### ISSUE THREAD

**Issue by mustafa0x** [linuxscout/fareh#2]
هذه قائمة أخطاء لغوية شائعة، جمعها أحدهم من كتب اللغة:

ومن الخطأ قولهم: خلوق/ وصوابه: حسن الأخلاق
و: مدبب/ ص: حاد الرأس
و: مدجج بالسلاح/ ص: مدجج في السلاح
و: دُرَّة عمر/ ص: دِرَّة عمر
و: دمغ/ ص: وسم
و: نفس الشيء/ ص: الشيء نفسه (إن لم يرد بالنفس الذات)
و: رئيسيَّة/ ص: رئيسة
و: رابعة النهار/ ص: رائعة النهار
و: على الرَّحب والسعة/ ص: على الرُّحب

ومن الخطأ قولهم: وقع في رَوْعي / وصوابه: رُوْعي
و: زيجة/ ص: زواج
و: زِيف / ص: زَيف
و: سميك / ص: ثخين
و: الصَرْعة / ص: الصُّرَعَة
و: يفْرُك مؤمن مؤمنة/ ص: يَفرَك
و: حُمُرِ النِّعَم/ ص: حُمْرِ النَّعَم
و: حُمَّة / ص: حُمَة
و: لا تعجَز/ ص: تَعجِز
و: مِفحَص قطاة/ ص: مَفْحَص
و: نَعِس الصبي / ص: نَعَسَ
و: الصبي حتى يكبُر / ص: يَكبَر 
و: يَعمَدُ إلى كذا/ ص: يَعمِدُ 
و: متسول / ص: سائل-شحَّاذ
و: مشبوه/ ص: مشتبه فيه 
و: شحِبَ لونه / ص: شَحَب-شَحُبَ
و: لا مَشاحَّة/ ص: لا مُشاحَّة
و: نظر شَذَرًا/ ص: شَزْرًا
و: أشرطة/ ص: شُرُط- شرائط

ومن الخطأ قولهم: تشكل الفريق من../ وصوابه: تكون من..
و: كتاب مُشَكَّل/ ص: مشكول- مُشكَل 
و: الشنب/ ص: الشارب 
و: شافاه الله/ ص: شفاه الله
و: صفحة (للورقة لا أحد وجهيها) / ص: صحيفة
و: صَمَّام- سدَّاد القارورة/ ص: صِمَام- سِدَاد 
و: طابور / ص: قطار 
و: طُحال (العضو)/ ص: طِحال 
و: طُلسُم / ص: طَلسَم- طِلسِم 
و: طَمَأنينة/ ص: طُمَأنينة
و: جَهُوري/ ص: جَهْوَري
و: مِنطاد/ ص: مُنطاد
و: طَهران/ ص: طِهران
.
تنبيه: أُلَخِّص مضمامين كتاب أقرأه، وليس شيءٌ من ذلك رأيي واجتهادي

ومن الخطأ قولهم: أحمر غامق/ صوابه: داكن
و:عُنيَ به فلان/ ص: عَنِيَ به
و: أبعد النَّجعَة/ ص: أبعد النُّجعَة
و: مفترق طرق/ ص: مَفرِقِ طرق
و: كل الصيد في جوف الفِرا/ ص: الفَرَا
و: مِفصَل/ ص: مَفصِل
و: فَطْحَل/ ص: فِطَحْل
و: فطاحل/ ص: فحول أو عظماء
و: استفهم منه عن الأمرِ/ ص: استفهمَهُ الأمرَ
و: تقابلت معه/ ص: قابلته
و: جلس قِبالته/ ص: قُبالَتَه
و: قَدِمَ زيدٌ إلى أرض كذا/ ص: قَدِمَ زيدٌ أرضَ كذا
و: ضرب به عَرْض الحائط/ ص: عُرْضَ الحائط

ومن الخطأ قولهم: اشترى كذا بأكمله/ صوابه: برمته
و: يَلفُظُ/ ص: يَلفِظُ
و: اللُّقاح/ ص: اللِّقاح
و: لواه لويًا/ ص: لَيًَّا
و: لا أدري (ما إذا-عمَّا إذا-إن) كنتَ راضيا أم لا/ ص: لا أدري أأنت راضٍ أم لا (فلا يرد ما سبق بعد أفعال القلوب)
و: مُدّ البصر/ ص: مَدّ (ومَدى أفصح) البصر
و: مزح معه/ ص: مازحه
و: انمسح/ ص: امَّحى
و: تمعَّن في النظر/ ص: أمعن في النظر
و: مها (للواحدة)/ ص: مهاة
و: ميِّزة/ ص: مِيزة- مَيْزَة
و: ميوعة/ ص: مَيْع
و: يُنبوع الغِواية الفكرية/ ص: يَنبوع الغَواية الفكرية

ومن الخطأ قولهم: نُدْبة/ صوابه: نَدَبَة
و: الإمام النِّسائي/ ص: النَّسائي
و: تنافسوا على الأمر/ ص: تنافسوا في الأمر
و: انتقص من حقه/ ص: انتقص حقَّه
و: نمَّلَت يده/ ص: نَمِلَت يده
و: رأيت منامًا/ ص: رأيت حُلُْمًا-رؤيا
و: نوَّه بكذا/ ص: أشار إلى كذا
و: نوايا/ ص: نيات
و: هَرَع إليه/ ص: هُرِعَ-أُهْرِعَ-أَهْرَع إليه
و: أهرامات/ ص: أهرام
و: هَضَبة/ ص: هَضْبَة
و: تهكم على فلان/ ص: تهكم بفلان
و: اهتَمَّ للأمر/ ص: اهتَمَّ بالأمر
و: مَهَمَّة عسكرية/ ص: مُهِمَّة عسكرية
و: هِنَة-هِنَات/ ص: هَنَة-هَنَات
و: رِعاع/ ص: رَُعاع
و: جَلَسَ لوحدِه/ ص: جَلَس وَحدَه
و: يورَمُ الجلد/ ص: يَرِمُ الجلد
و: وُلُوع زيد بالشعر عظيمٌ/ ص: وَلُوع

ومن الخطأ قولهم: كافة الرجال/ والصحيح: الرجال كافة
و: مسبق/ ص: سابق
و: ملغية/ ص:ملغاة

**Comment by linuxscout** [comment]
شكرا أخي مصطفى
سنضيف ما ليس موجودت في القائمة
بارك الله فيك

**Comment by mustafa0x** [comment]
وفيكم بارك

فرحت جدا بهذا المشروع، بل قد كان في بالي من فترة.

ولي أداة للتحسينات السطحية:
https://nuqayah.com/tools/text.html

المصدر: https://github.com/mustafa0x/ar-text-tools/blob/master/assets/repls.js

**Comment by linuxscout** [comment]
وعليكم السلام
الموقع جميل مفيد جدا
سأقتبس منه بعض الأفكار المفيدة
بارك الله فيه
هناك مشروع غلطاوي فيه قائمة بالأخطاء الشائعة للكلمات مثل الضاد والظاء، سيكون مفيدا جدا لموقعك

**Comment by linuxscout** [comment]
تم إعداد البيانات وإضافتها للمدقق النحوي

* التنظيف وحذف المكرر المنفذ سابق أعطى 74 قاعدة
* أضيفت 50 قاعدة حتى الآن 50/74

**Comment by mustafa0x** [comment]
جزاكم الله خيرا

عمل رائع

> هناك مشروع غلطاوي فيه قائمة بالأخطاء الشائعة للكلمات مثل الضاد والظاء، سيكون مفيدا جدا لموقعك

جميل! سأطلع عليه إن شاء الله
