### ISSUE TITLE
تجنب صيغة ods

### ISSUE THREAD

**Issue by engahmadkadi** [linuxscout/fareh#23]
السلام عليكم أخي طه،

لا يخفى عليك في d411af24d9e33c7fc4290c961f46b53cabf80bb4، أن إظهار الفرق بين ال commit السابقة والحالية غير متاح لأن صيغة الملف المستخدمة هي ods. هل يمكن تحويل الصيغة إلى صيغة أخرى أبسط، مثل csv ليتمكن لنا معرفة التعديلات المُجرَيَة؟ و هذا إلى ذلك يسهل عليك قبول أو رفض طلبات دمج فروع الخازنة إلى جذعها (أو فرعها) الرئيسي وقتما تُرسَل إليك من مبرمجين آخرين.

و شكراً

**Comment by linuxscout** [comment]
معك حق، أضفت الملف الذي طلبته
