### ISSUE TITLE
رسالة خطأ غير واضحة في تأكد و تحصل

### ISSUE THREAD

**Issue by zayedalsaidi** [linuxscout/fareh#5]
حاليا الجملة التالية 
تأكّد من أن البيانات
تعطي خطأ: يفضل أن يقال: "تأكّد" "تأكّد" ، وهذا لا معنى له، وأظن أن المشكلة في أن تأكد فعل يتعدى لمفعولين دون حرف جر.
كذلك الجملة التالية:
تحصل على خمسة قروش
 تعطي: (تَحَصَّل الشيءُ): تَجَمَّعَ وثبت "حصل" ، ولكن أظنها نفس المشكلة السابقة.

**Comment by linuxscout** [comment]
بالنسبة للجملة الأولى:
وجود التشكيل جعل الاقتراح خاطئا لأنني أستعمل استبدالا بتعبير منتظم
regex_replace

الثانية،
هي أن الأفعال الخماسية مثل تحصّل يلتبس في كثير من حالاتها بفعلها المجرد
يعني هو تحصّل، وهي تحصٌل

هذه التوضيحات للعودة إليها في العمل

**Comment by linuxscout** [comment]
وجدت حلا للمشكلة،
أرفعه للمستودع،
سينتظر دمجه في الإصدار الرسمي
