### ISSUE TITLE
إضافة لام التعريف في في تصحيح الرئيسية

### ISSUE THREAD

**Issue by zayedalsaidi** [linuxscout/fareh#6]
حاليا عندما يكتشف المدقق خطأ في نسبة الرئيس، و تكون معرفة يعطيك اقتراح غير معرف مثال:
مراجعة الأقران الرئيسية
يعطي اقتراحين:
رئيس و رئيسة
مما يضطرنا إلى التدخل اليدوي للإصلاح المشكلة.

**Comment by linuxscout** [comment]
حسنا،
عدلت عليها من أجل الأمثلة:
الصفحة الرئيسية
والمقال الرئيسي،
لكن ما زلت أواجه مشكلة مع جمع التكسير في التوافق مع الصفة
