### ISSUE TITLE
الذي و التي

### ISSUE THREAD

**Issue by zayedalsaidi** [linuxscout/fareh#7]
حاليا المصحح يعطي خطأ كاذب على هذه الأمثلة:
من أجل الطرق التي قد تسير فيها بشكل خاطئ
أنظمة الحاسوب التي تتطلب المصادقة
اختبار الوحدة الأساسي، والذي ينجح

يبدو أن المصحح يختبر المضاف للتميز بين المذكر والمؤنث وليس المضاف إليه.

**Comment by linuxscout** [comment]
> من أجل الطرق التي قد تسير فيها بشكل خاطئ
> أنظمة الحاسوب التي تتطلب المصادقة
الاقتراح يعمل على الكلمة الأخيرة
لذا تساءل عن الذي بعد الحاسوب،
أعتقد أنه يجب تعديل القاعدة لإخراج الاقتراح بشكل أفضل

> اختبار الوحدة الأساسي، والذي ينجح
هنا نقصد "والذي" الذي هو تعبير ركيك
