### ISSUE TITLE
هذه القيم

### ISSUE THREAD

**Issue by zayedalsaidi** [linuxscout/fareh#8]
يبدو أن المصحح لا يتعرف صيغة الجمع  التي على وزن فِعَل (من فِعْلة) ويحسبها مذكرة:
هذه القيم
هذه القطع
هذه الحلي
هذه البيع
هذه البدع
الجدير بالملاحظة أن هذه المفردات لا تعطي رسالة خطأ:
هذه اللحى
هذه الهرر

**Comment by linuxscout** [comment]
نفس مشكلة العدد،
عندي مشكلة في جمع التكسير
وذلك لأنني وضمته بالتأنيث لكل مشكلة الصفة المفردة المؤنثة مثل
" الأعداد السالبة"

**Comment by linuxscout** [comment]
Solved
